import { test, expect } from '@playwright/test';

test('test KIB', async ({ page }) => {
  await page.goto('https://kib-connect-demo-store-4.myshopify.com/password');
  await page.getByText('KIB Connect Demo Store').click();
  await expect(page.getByText('Enter store password')).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Enter store password' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Enter store password' }).click();
  await page.getByRole('textbox', { name: 'Enter store password' }).fill('Test123');
  await page.getByRole('button', { name: 'Enter' }).click();
  await page.locator('#product-card-ARHJPVGNQY1N2RnlDb__static-product-card-1 product-title').click();
  await expect(page.getByRole('heading', { name: 'Test Product' })).toBeVisible();
  await page.getByRole('button', { name: 'Buy it now' }).click();
  await expect(page.getByRole('heading', { name: 'Contact' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Email or mobile phone number' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Email or mobile phone number' }).click();
  await page.getByRole('textbox', { name: 'Email or mobile phone number' }).fill('(307) 682-8835');
  await page.getByRole('heading', { name: 'Delivery' }).click();
  await expect(page.locator('#Select1566')).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Last name' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Last name' }).click();
  await page.getByRole('textbox', { name: 'Last name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Last name' }).fill('T');
  await page.getByRole('textbox', { name: 'Last name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Last name' }).fill('Test');
  await expect(page.getByRole('combobox', { name: 'Address' })).toBeVisible();
  await page.getByRole('combobox', { name: 'Address' }).click();
  await page.getByRole('combobox', { name: 'Address' }).fill('362 Ridgewood Dr, Soldotna, Alaska 99669, USA');
  await expect(page.locator('circle').first()).toBeVisible();
  await page.getByRole('combobox', { name: 'Address' }).click();
  await page.getByRole('combobox', { name: 'Address' }).click();
  await page.locator('div').filter({ hasText: /^Suggestions$/ }).click();
  await expect(page.getByRole('combobox', { name: 'Address' })).toBeVisible();
  await page.getByRole('combobox', { name: 'Address' }).dblclick();
  await page.getByRole('combobox', { name: 'Address' }).click();
  await page.getByRole('option', { name: '362 Ridgewood Dr, Soldotna,' }).click();
  await page.getByRole('textbox', { name: 'Phone', exact: true }).click();
  await page.getByRole('textbox', { name: 'Phone', exact: true }).click();
  await page.getByRole('textbox', { name: 'Phone', exact: true }).fill('(307) 682-8835');
  await page.getByRole('button', { name: 'Complete order' }).click();
  await page.locator('#PaymentErrorBanner').dblclick();
  await expect(page.getByText('You’ve reached the limit for')).toBeVisible();
});